# Generated by Django 4.2.2 on 2025-05-12 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('character_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='ユーザー名')),
                ('default_character_id', models.IntegerField(default=1, verbose_name='デフォルトキャラクターID')),
                ('is_staff', models.BooleanField(default=False, help_text='このユーザーがAdminサイトにログインできるか指定します。', verbose_name='スタッフステータス')),
                ('is_active', models.BooleanField(default=True, help_text='このユーザーがアクティブとして扱われるか指定します。非選択にするとユーザーを解除する代わりにアカウントを削除されます。', verbose_name='アクティブ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='accounts_users_set', related_query_name='account_user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='accounts_user_permissions', related_query_name='account_user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'ユーザー',
                'verbose_name_plural': 'ユーザー一覧',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserCharacterAffinity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affinity_value', models.IntegerField(default=0, verbose_name='親密度')),
                ('is_default_character', models.BooleanField(default=False, verbose_name='デフォルトキャラクターフラグ')),
                ('selected_audio_voice_id', models.IntegerField(blank=True, null=True, verbose_name='選択音声ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character_management.characters', verbose_name='キャラクター')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'ユーザーとキャラクターの関連',
                'verbose_name_plural': 'ユーザーとキャラクターの関連一覧',
                'ordering': ['user', 'character'],
                'unique_together': {('user', 'character')},
            },
        ),
    ]
