# Generated by Django 4.2.2 on 2025-05-12 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='キャラクター名')),
                ('description', models.TextField(verbose_name='キャラクター説明')),
                ('default_image_category', models.CharField(default='default', max_length=50, verbose_name='画像カテゴリ')),
                ('default_audio_voice_id', models.IntegerField(blank=True, null=True, verbose_name='デフォルト音声ID')),
                ('default_audio_on', models.BooleanField(default=False, verbose_name='デフォルト音声ON/OFF')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'キャラクター',
                'verbose_name_plural': 'キャラクター一覧',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affinity_level', models.IntegerField(blank=True, null=True, verbose_name='親密度レベル')),
                ('category', models.CharField(default='default', help_text='例: default, happy, sad など。Charactersモデルのdefault_image_categoryと対応します。', max_length=50, verbose_name='画像カテゴリ')),
                ('file_name', models.CharField(max_length=255, null=True, verbose_name='画像ファイル名/パス')),
                ('trigger_condition', models.CharField(blank=True, max_length=255, null=True, verbose_name='表示トリガー条件')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character_management.characters', verbose_name='キャラクター')),
            ],
            options={
                'verbose_name': '画像',
                'verbose_name_plural': '画像一覧',
                'ordering': ['character', 'category', 'file_name'],
                'unique_together': {('character', 'category', 'file_name')},
            },
        ),
    ]
