# Generated by Django 4.2.2 on 2025-05-12 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('character_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=10, verbose_name='発言者')),
                ('content', models.TextField(verbose_name='発言内容')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='発言日時')),
                ('sentiment_score', models.FloatField(blank=True, null=True, verbose_name='感情分析スコア')),
                ('affinity_change_applied', models.IntegerField(blank=True, null=True, verbose_name='適用された親密度変動')),
                ('affinity_rules_triggered', models.TextField(blank=True, null=True, verbose_name='トリガーされた親密度ルール')),
                ('affinity_value_after', models.IntegerField(blank=True, null=True, verbose_name='ターン後の親密度')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character_management.characters', verbose_name='キャラクター')),
                ('selected_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='character_management.image', verbose_name='表示された画像')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '会話履歴',
                'verbose_name_plural': '会話履歴一覧',
                'ordering': ['-timestamp'],
            },
        ),
    ]
